FROM node:16-alpine3.13

WORKDIR /opt/usr

RUN npm install 

RUN apt-get update && \
    DEBIAN_FRONTEND="nointeractive" \
    apt-get install -y --no-install-recommends \
    chromium=86.0.4240.111-r0 \
    libgconf-2-4 \
    openjdk-8-jre-headless \
    && rm -rf /var/lib/apt/lists/*

CMD ["npm", "run", "e2e"]