apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddevops
  labels:
    app: clouddevops
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clouddevops
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clouddevops
    spec:
      containers:
        - image: ciregbu/clouddevops:latest
          imagePullPolicy: Always
          name: clouddevops
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: clouddevops
  labels:
    app: clouddevops
spec:
  type: LoadBalancer
  selector:
    app: clouddevops
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
