apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deploy
  labels:
    app: angularapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angularapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: angularapp
    spec:
      containers:
      - name: angular-pod
        imagePullPolicy: Always
        image: ciregbu/devops:1.0
        ports:
        - containerPort: 8000

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: angular-deploy
#   labels:
#     app: angularapp
# spec:
#   type: LoadBalancer
#   selector:
#     app: angularapp
#   ports:
#     - port: 8000
#       targetPort: 8000
#       nodePort: 8000
#       protocol: TCP
