apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularapp-deployment
  labels:
    app: angularapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angularapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: angularapp
    spec:
      containers:
        - image: ciregbu/angularapp:1.0
          imagePullPolicy: Always
          name: angularapp
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: angularapp
  labels:
    app: angularapp
spec:
  type: LoadBalancer
  selector:
    app: angularapp
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
