version: 2.1

orbs:
  slack: circleci/slack@4.2.0
  aws-cli: circleci/aws-cli@2.0.3 
  aws-eks: circleci/aws-eks@0.2.3

jobs:
  build-app:
    docker:
      - image: circleci/node:16.13.0
    
    # The current directory will be the place where all the steps will run
    working_directory: ~/project

    steps:
      # Checkout the code from the git branch into the working_directory
      - checkout
      # Log the current branch for debugging purposes
      - run:
          name: Log the current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies (node_modules) from the CircleCI cache if it exists
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies in CircleCI storage if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
              - node_modules
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: 
            npm update
            ng update
            ng update--all--force
      - run:
          name: Build app
          command: |
            sudo npm i
            npm run build

  # Lint the frontend source code
  lint-app:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - restore_cache:
          key: frontend-build
      - run:
          name: Lint frontend
          command:
            npm ci
            npm run lint

  lint-docker:
    docker: 
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          key: frontend-build
      - run:
          name: Lint docker
          command: |
            python3 -m venv venv
            . venv/bin/activate
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            hadolint ./Dockerfile

  # Scan for known vulnerabilities
  scan-app:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - run:
          name: Scan application files
          command: npm install

  test-app:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - restore_cache:
          key: frontend-build
      # Test the source code
      - run:
          name: Test frontend source code
          command: 
            sudo npm install -g karma-cli
            npm run test --code-coverage
      - run:
          name: Run E2E tests
          command: npm run

  build-and-push-image: 
    machine: true
    steps:
      - checkout
      - run:
          name: Create repository
          command:
            aws ecr create-repository --region ${AWS_DEFAULT_REGION} --repository-name ${REPO_NAME}
      - run:
          name: Build docker container  # https://dzone.com/articles/how-to-dockerize-angular-app
          command: |
            docker login --username ${DOCKER_LOGIN} --password ${Docker_PWD}
            docker build -t angularapp:1.0 . 
            docker images ls
            docker tag angularapp ${DOCKER_LOGIN}/angularapp:1.0
            docker push ${DOCKER_LOGIN}/angularapp:1.0

  # Deploy the angular app
  deploy-app:
      docker:
        - image: circleci/node:16.13.0
      working_directory: ~/project
      steps:
        - checkout
        - restore_cache:
            key: frontend-build
        - run:
            name: Install AWS CLI dependencies
            command: |
              sudo apt-get update && sudo apt-get install -yy less
              sudo apt-get install unzip -y
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
        - run:
            name: Deploy Docker Container Image to Amazon ECR
            command: |
              echo "Authenticating Docker client to AWS ECR registry..."
              aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 471776097205.dkr.ecr.eu-west-2.amazonaws.com

              echo "Building the container locally..."
              docker build -t 471776097205.dkr.ecr.eu-west-2.amazonaws.com/angularapp1.0 .

              echo "Tagging the image so that it can be pushed to the repository..."
              docker tag angularapp:1.0 471776097205.dkr.ecr.eu-west-2.amazonaws.com/angularapp:1.0

              echo "Pushing the image the newly created Amazon repository..."              
              docker push 471776097205.dkr.ecr.eu-west-2.amazonaws.com/angularapp:1.0

              echo "Docker image upload completed!"
workflows:
    default:
      jobs:
        - build-app
        - scan-app:
            requires: [build-app]
        - lint-app:
            requires: [build-app]
        - lint-docker:
            requires: [lint-app, build-app]
        - test-app:
            requires: [build-app]
        - build-and-push-image:
            requires: [test-app, lint-app, lint-docker]
            filters:
              branches:
                only: [master]
        # The deploy job will only run on the filtered branches and
        # require the build job to be successful before it starts
        - deploy-app:
            requires: [build-and-push-image]
            filters:
              branches:
                only:
                  - master